INSERT INTO pmm.auth_permission VALUES ('1','Can add log entry',1,'add_logentry');
INSERT INTO pmm.auth_permission VALUES ('2','Can change log entry',1,'change_logentry');
INSERT INTO pmm.auth_permission VALUES ('3','Can delete log entry',1,'delete_logentry');
INSERT INTO pmm.auth_permission VALUES ('4','Can add permission',2,'add_permission');
INSERT INTO pmm.auth_permission VALUES ('5','Can change permission',2,'change_permission');
INSERT INTO pmm.auth_permission VALUES ('6','Can delete permission',2,'delete_permission');
INSERT INTO pmm.auth_permission VALUES ('7','Can add group',3,'add_group');
INSERT INTO pmm.auth_permission VALUES ('8','Can change group',3,'change_group');
INSERT INTO pmm.auth_permission VALUES ('9','Can delete group',3,'delete_group');
INSERT INTO pmm.auth_permission VALUES ('10','Can add user',4,'add_user');
INSERT INTO pmm.auth_permission VALUES ('11','Can change user',4,'change_user');
INSERT INTO pmm.auth_permission VALUES ('12','Can delete user',4,'delete_user');
INSERT INTO pmm.auth_permission VALUES ('13','Can add content type',5,'add_contenttype');
INSERT INTO pmm.auth_permission VALUES ('14','Can change content type',5,'change_contenttype');
INSERT INTO pmm.auth_permission VALUES ('15','Can delete content type',5,'delete_contenttype');
INSERT INTO pmm.auth_permission VALUES ('16','Can add session',6,'add_session');
INSERT INTO pmm.auth_permission VALUES ('17','Can change session',6,'change_session');
INSERT INTO pmm.auth_permission VALUES ('18','Can delete session',6,'delete_session');
INSERT INTO pmm.auth_permission VALUES ('19','Can add site',7,'add_site');
INSERT INTO pmm.auth_permission VALUES ('20','Can change site',7,'change_site');
INSERT INTO pmm.auth_permission VALUES ('21','Can delete site',7,'delete_site');
INSERT INTO pmm.auth_permission VALUES ('22','Can add user profile',8,'add_userprofile');
INSERT INTO pmm.auth_permission VALUES ('23','Can change user profile',8,'change_userprofile');
INSERT INTO pmm.auth_permission VALUES ('24','Can delete user profile',8,'delete_userprofile');
INSERT INTO pmm.auth_permission VALUES ('25','Can add proyecto',9,'add_proyecto');
INSERT INTO pmm.auth_permission VALUES ('26','Can change proyecto',9,'change_proyecto');
INSERT INTO pmm.auth_permission VALUES ('27','Can delete proyecto',9,'delete_proyecto');
INSERT INTO pmm.auth_permission VALUES ('28','Can add usuario proyecto',10,'add_usuarioproyecto');
INSERT INTO pmm.auth_permission VALUES ('29','Can change usuario proyecto',10,'change_usuarioproyecto');
INSERT INTO pmm.auth_permission VALUES ('30','Can delete usuario proyecto',10,'delete_usuarioproyecto');
INSERT INTO pmm.auth_permission VALUES ('31','Can add fase',11,'add_fase');
INSERT INTO pmm.auth_permission VALUES ('32','Can change fase',11,'change_fase');
INSERT INTO pmm.auth_permission VALUES ('33','Can delete fase',11,'delete_fase');
INSERT INTO pmm.auth_permission VALUES ('34','Can add comite',12,'add_comite');
INSERT INTO pmm.auth_permission VALUES ('35','Can change comite',12,'change_comite');
INSERT INTO pmm.auth_permission VALUES ('36','Can delete comite',12,'delete_comite');
INSERT INTO pmm.auth_permission VALUES ('37','Can add atributo',13,'add_atributo');
INSERT INTO pmm.auth_permission VALUES ('38','Can change atributo',13,'change_atributo');
INSERT INTO pmm.auth_permission VALUES ('39','Can delete atributo',13,'delete_atributo');
INSERT INTO pmm.auth_permission VALUES ('40','Can add tipo item',14,'add_tipoitem');
INSERT INTO pmm.auth_permission VALUES ('41','Can change tipo item',14,'change_tipoitem');
INSERT INTO pmm.auth_permission VALUES ('42','Can delete tipo item',14,'delete_tipoitem');
INSERT INTO pmm.auth_permission VALUES ('43','Can add atributo tipo item',15,'add_atributotipoitem');
INSERT INTO pmm.auth_permission VALUES ('44','Can change atributo tipo item',15,'change_atributotipoitem');
INSERT INTO pmm.auth_permission VALUES ('45','Can delete atributo tipo item',15,'delete_atributotipoitem');
INSERT INTO pmm.auth_permission VALUES ('46','Can add tipo item proyecto',16,'add_tipoitemproyecto');
INSERT INTO pmm.auth_permission VALUES ('47','Can change tipo item proyecto',16,'change_tipoitemproyecto');
INSERT INTO pmm.auth_permission VALUES ('48','Can delete tipo item proyecto',16,'delete_tipoitemproyecto');
INSERT INTO pmm.auth_permission VALUES ('49','Can add item',17,'add_item');
INSERT INTO pmm.auth_permission VALUES ('50','Can change item',17,'change_item');
INSERT INTO pmm.auth_permission VALUES ('51','Can delete item',17,'delete_item');
