INSERT INTO pmm.des_tipo VALUES (1,'NUEVO REQUISITO');
INSERT INTO pmm.des_tipo VALUES (2,'CAMBIO EN REQUISITO');
INSERT INTO pmm.des_tipo VALUES (3,'CAMBIO EN EL DISENHO');
INSERT INTO pmm.des_tipo VALUES (4,'PROBLEMA CON EL SOFTWARE');
INSERT INTO pmm.des_tipo VALUES (5,'PROBLEMA DE INTERFAZ DE USUARIO');
INSERT INTO pmm.des_tipo VALUES (6,'ERROR EN LA DOCUMENTACION');
INSERT INTO pmm.des_tipo VALUES (7,'SUGERENCIA DE MEJORA');
SELECT setval('pmm.des_tipo_id_tipo_seq', 8, false);